apiVersion: batch/v1
kind: Job
metadata:
  name: blaster
spec:
  template:
    spec:
      containers:
      - name: blaster
        image: asia.gcr.io/airasia-opdatalake-stg/blaster-cli:latest
        env:
          - name: TARGET_URI
            value: http://snowman.opdl.stg.data.airasiainternal.net/com.snowplowanalytics.snowplow/tp2
          - name: WORKERS
            value: "100"
          - name: REQUESTS
            value: "100"
