apiVersion: batch/v1
kind: Job
metadata:
  name: blaster
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: blaster
        image: asia.gcr.io/airasia-opdatalake-stg/blaster
        command: ["/root/blast"]
        args: ["$(TARGET_URI)","-w","$(WORKERS)","-r","$(REQUESTS)"]
        env:
          - name: TARGET_URI
            value: http://snowman.opdl.stg.data.airasiainternal.net
          - name: WORKERS
            value: "50"
          - name: REQUESTS
            value: "10"
      restartPolicy: Never
  backoffLimit: 4
